sources:
  - source_name: global_power_plants_synthetic_records_v2
    enabled: true
    format: csv
    path: datasets/global_power_plants_synthetic_records_v2.csv
    primary_key: plant_id
    event_time_column: commissioning_year

  - source_name: global_power_plants_synthetic_records
    enabled: true
    format: csv
    path: datasets/global_power_plants_synthetic.csv
    primary_key: plant_id
    event_time_column: commissioning_year
