sources:
  - source_name: wri_global_power_plants
    enabled: true
    format: kagglehub
    dataset: ibrahimqasimi/global-power-plants-database-wri
    file_path: ""
    primary_key: plant_id
    event_time_column: last_updated_at

  - source_name: kaggle_energy
    enabled: true
    format: kagglehub
    dataset: sujaykapadnis/energy
    file_path: ""
    primary_key: energy_record_id
    event_time_column: date

  - source_name: open_power_systems_data
    enabled: true
    format: kagglehub
    dataset: jordansiem/open-power-systems-data
    file_path: ""
    primary_key: generation_id
    event_time_column: generation_date

  - source_name: carbon_emissions
    enabled: true
    format: kagglehub
    dataset: saloni1712/co2-emissions
    file_path: ""
    primary_key: emission_id
    event_time_column: year

  - source_name: renewable_adoption
    enabled: true
    format: kagglehub
    dataset: taruneshburman/renewable-energy-adoption-dataset
    file_path: ""
    primary_key: adoption_id
    event_time_column: year

  - source_name: weather_observations
    enabled: true
    format: kagglehub
    dataset: muthuj7/weather-dataset
    file_path: ""
    primary_key: weather_record_id
    event_time_column: date
